swagger: "2.0"
info:
  title: Your API
  version: 1.0.0
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: "Bearer token for authentication"
security:
  - Bearer: []
